import React from "react";
export const experiences = [
    
    {
        isFreelance: false,
        time:"02/2021-04/2021",
        company:"Proconsi",
        category: "FULLSTACK",
        rol:"Full Stack",
        name:"User Manager App",
        taskManagment: "jira",
        backend:  ["Java 8", "Spring Boot"],
        frontend:["JS","CSS", "Boostrap", "jQuery", "Ajax"],
        dataBase:["MySql", "Oracle", "MariaDB"],
        container: "Docker",
        repository:["GitHub"],
        methodology:["Agile", "Scrum", "Solid"],
        description: "In this project, I developed an app designed for global management of both internal users and clients, tailored specifically to their respective roles."
    },
    {
        isFreelance: false,
        time:"04/2021-06/2021",
        company:"Proconsi",
        category: "FULLSTACK",
        rol:"Full Stack",
        name:"GPS Mapping App",
        taskManagment: "jira",
        backend: ["PHP","Laravel"],
        frontend:["JS", "CSS", "Boostrap", "React"],
        dataBase:["MySql", "Oracle", "MariaDB"],
        container: "Docker",
        repository:["GitHub"],
        methodology:["Agile", "Scrum", "Solid"],
        description: "In this project, I worked on a GPS mapping system used by both public and private transport sectors. My role in this implementation was as a full stack developer. I developed the frontend view of the mapping system and handled the backend logic to extract and process data from APIs."
    },
    {
        isFreelance: false,
        time:"06/2021-08/2021",
        company:"IDE Comunicacion",
        category: "FULLSTACK",
        rol:"Full Stack Developer",
        name:"Vodafone Mobile App",
        taskManagment: "jira",
        backend:  ["PHP", "Laravel"],
        frontend:["JS","CSS", "Boostrap", "jQuery", "Ajax"],
        dataBase:["MySql", "Oracle", "MariaDB"],
        container: "Docker",
        repository:["GitHub"],
        methodology:["Agile", "Scrum", "Solid"],
        description: "In this position, I was responsible for developing software to manage advertising campaigns for multinational companies in the mobile telephony sector. Additionally, I led the end-to-end development of the main app for managing company resources in the Galicia region. The technologies used included PHP and Laravel for the backend, Oracle and MySQL for databases, and React, JavaScript, CSS, and Bootstrap for the frontend."
    },
    {
        isFreelance: true,
        time:"08/2022-10/2022",
        company:"European University",
        category: "BLOCKCHAIN",
        rol:"BLOCKCHAIN DEVELOPER",
        name:"Cars Trazability system",
        taskManagment: "gitHub issues",
        backend: ["java"],
        frontend:["React","JS","CSS", "Boostrap", "truffle"],
        smartContract: ["solidity"],
        exchangeManager: ["Uniswap"],
        wallet:["Metamask"],
        dataBase:["PostgresSQL"],
        container: "Docker",
        repository:["GitHub"],
        methodology:["Agile", "Scrum", "Solid"],
        description: "I developed a blockchain-based traceability system for tracking parts and production sequences in automotive assembly lines."
    },
    {
        isFreelance: false,
        time:"08/2021-10/2021",
        company:"IDE Comunicacion",
        category: "FULLSTACK",
        rol:"Full Stack Developer",
        name:"Maintenance of APPS",
        taskManagment: "jira",
        backend:  ["java", "Spring"],
        frontend:["JS","CSS", "Boostrap", "jQuery", "Ajax"],
        dataBase:["MySql", "Oracle", "MariaDB"],
        container: "Docker",
        repository:["GitHub"],
        methodology:["Agile", "Scrum", "Solid"],
        description: "I participated in the implementation of new features in existing products designed with Java Spring for the backend. In this role, I worked directly with the client and coordinated the layout team with the design team."
    },
    {
        isFreelance: false,
        time:"10/2021-05/2022",
        company:"CDS, a Hewlett Packard Enterprise company",
        category: "FULLSTACK",
        rol:"BUSINESS APPLICATION ENGINEER",
        name:"LUCA APP",
        taskManagment: "jira",
        backend: ["java", "Spring"],
        frontend:["React","JS","CSS", "Boostrap", "jQuery", "Ajax"],
        dataBase:["Oracle"],
        container: "Docker",
        repository:["GitHub"],
        methodology:["Agile", "Scrum", "Solid"],
        description: "I developed the hiring and general personnel management app for CDS, Hewlett Packard Enterprise Company (LUCA), from end to end. Additionally, I was responsible for maintaining the company's main app for overall internal management. "
    },
    {
        isFreelance: false,
        time:"05/2022-10/2022",
        company:"CDS, a Hewlett Packard Enterprise company",
        category: "FULLSTACK",
        rol:"BUSINESS APPLICATION ENGINEER",
        name:"Tech Challenge APP",
        taskManagment: "jira",
        backend: ["java", "Spring"],
        frontend:["React","JS","CSS", "Boostrap", "jQuery", "Ajax"],
        dataBase:["SQLServer"],
        container: "Docker",
        repository:["GitHub"],
        methodology:["Agile", "Scrum", "Solid"],
        description: "Acted as the lead developer for the web app used in the hiring hackathon for CDS, Hewlett Packard Enterprise Company."
    },
    {    
        isFreelance: true,
        time:"10/2022-03/2023",
        company:"European University",
        category: "BLOCKCHAIN",
        rol:"BLOCKCHAIN DEVELOPER",
        name:"Electrochain",
        taskManagment: "gitHub issues",
        backend: ["java"],
        frontend:["React","JS","CSS", "Boostrap", "truffle"],
        smartContract: ["solidity"],
        exchangeManager: ["Uniswap"],
        wallet:["Metamask"],
        dataBase:["PostgresSQL"],
        container: "Docker",
        repository:["GitHub"],
        methodology:["Agile", "Scrum", "Solid"],
        description: "I developed a web app with a tokenization system for renewable energies, which calculates the price of energy in kWh in real time using Java microservices. The app also included a user management system and a transaction management system for sustainable urbanizations."
    },
    {
        isFreelance: false,
        time:"10/2022-06/2023",
        company:"CDS, a Hewlett Packard Enterprise company",
        category: "FULLSTACK",
        rol:"BUSINESS APPLICATION ENGINEER",
        name:"My Recruitment APP",
        taskManagment: "jira",
        backend: ["java", "Spring"],
        frontend:["React","JS","CSS", "Boostrap", "jQuery", "Ajax"],
        dataBase:["SQLServer"],
        container: "Docker",
        repository:["GitHub"],
        methodology:["Agile", "Scrum", "Solid"],
        description: "I developed the main app at an international level for hiring and managing internal personnel within the company."
    },
    {
        isFreelance: false,
        time:"06/2023-02/2024",
        company:"CDS, a Hewlett Packard Enterprise company",
        category: "DATAENGINEER",
        rol:"BUSINESS APPLICATION ENGINEER II",
        name:"Data engineering project ETLS",
        taskManagment: "jira",
        backend: ["Python", "SQL Alchemyst"],
        managmentAPI:["GraphQL", "Nemo"],
        dataBase:["MySql", "Oracle", "MariaDB", "DB2", "SQLServer"],
        container: "Docker",
        repository:["GitHub", "Bitbucket", "GitLab"],
        methodology:["Agile", "Scrum", "Solid"],
        description: "I have developed ETLs and data engineering systems to manage big data for multinational companies using APIs as the lead data engineer. Additionally, I have developed and maintained the working environment."
    },
    {
        isFreelance: false,
        time:"06/2023-02/2024",
        company:"CDS, a Hewlett Packard Enterprise company",
        category: "DATAENGINEER",
        rol:"BUSINESS APPLICATION ENGINEER II",
        name:"Data engineering project Notification System",
        taskManagment: "jira",
        backend: ["Python", "SQL Alchemyst"],
        managmentAPI:["GraphQL", "Nemo"],
        notificationTool: ["Hermes" ,"Power Automate"],
        dataBase:["MySql", "Oracle", "MariaDB", "DB2", "SQLServer"],
        container: "Docker",
        repository:["GitHub", "Bitbucket", "GitLab"],
        methodology:["Agile", "Scrum", "Solid"],
        description: "I developed a notification system to inform responsible parties about data status and role relationships within the area. Additionally, I maintained the big data engineering systems and led the automation and data engineering team."
    },
    {
        isFreelance: true,
        time:"02/2024-05/2024",
        company:"Private Sector",
        category: "FULLSTACK",
        rol:"FULL STACK DEVELOPER",
        name:"Bias test app",
        taskManagment: "gitHub issues",
        backend: ["java"],
        frontend:["React","JS","CSS", "Boostrap", "truffle"],
        notificationTool: ["Hermes"],
        exchangeManager: ["Uniswap"],
        wallet:["Metamask"],
        dataBase:["SQLServer"],
        container: "Docker",
        repository:["GitHub"],
        methodology:["Agile", "Scrum", "Solid"],
        description: "Development of a web application to conduct bias testing based on principles of behavioral psychology."
    }
]